server:
  servlet:
    context-path: /calc
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048
spring:
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: non_null
